#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo " Running build before push..."
npm run build

if [ $? -ne 0 ]; then
  echo "Build failed. Cannot push."
  exit 1
fi

echo "Build successful! Pushing..."